name: RandomDialogue
version: ${version}
description: A plugin that generates random dialogue responses using LLM
main: com.randomdialogue.RandomDialogueMod
api-version: 1.21.7
authors: [voidfemme]

commands:
  randomdialogue:
    description: Admin command for Random Dialogue plugin
    usage: /randomdialogue <subcommand>

permissions:
  randomdialogue.admin:
    description: Allows full access to Random Dialogue admin commands
    default: op
  randomdialogue.use:
    description: Allows basic use of RandomDialogue features
    default: true
